import { AdmissionFormState } from './types';

export const defaultFormData: AdmissionFormState = {
  fullNameBangla: '',
  fullNameEnglish: '',
  fatherName: '',
  fatherNID: '',
  motherName: '',
  motherNID: '',
  dateOfBirth: '',
  gender: '',
  religion: '',
  nationality: '',
  nid: '',
  birthCertificate: '',
  bloodGroup: '',
  maritalStatus: '',

  mobile: '',
  email: '',
  guardianMobile: '',
  presentAddress: '',
  presentDivision: '',
  presentDistrict: '',
  presentUpazila: '',
  presentPoliceStation: '',
  presentPostOffice: '',
  presentMunicipalityUnion: '',
  presentVillageNeighborhood: '',
  presentWard: '',
  permanentAddress: '',
  permanentDivision: '',
  permanentDistrict: '',
  permanentUpazila: '',
  permanentPoliceStation: '',
  permanentPostOffice: '',
  permanentMunicipalityUnion: '',
  permanentVillageNeighborhood: '',
  permanentWard: '',
  sameAsPresent: false,

  sscBoard: '',
  sscRoll: '',
  sscYear: '',
  sscGPA: '',
  sscGroup: '',
  sscInstitution: '',

  department: '',
  shift: '',
  session: '',
  semester: '',
  admissionType: '',
  group: '',

  photo: null,
  signature: null,
  sscMarksheet: null,
  sscCertificate: null,
  birthCertificateDoc: null,
  studentNIDCopy: null,
  fatherNIDFront: null,
  fatherNIDBack: null,
  motherNIDFront: null,
  motherNIDBack: null,
  testimonial: null,
  medicalCertificate: null,
  quotaDocument: null,
  extraCertificates: null,
};

